// Robot type definition
export interface Robot {
  name: string;
  purpose: string;
  movement: string;
  environment: string;
  control: string;
  sensors: string[];
}

// List of robot definitions for the Guess‑Who game.
// Each robot entry defines its name and functional attributes.

export const robots: Robot[] = [
  {
    name: "Sidewalk Delivery Bot",
    purpose: "Delivery",
    movement: "Wheels",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Camera", "LIDAR", "GPS", "Ultrasonic sensors", "IMU", "Infrared sensors"],
  },
  {
    name: "Warehouse Picker Bot",
    purpose: "Delivery",
    movement: "Wheels",
    environment: "Indoors",
    control: "Fully autonomous",
    sensors: ["Camera", "Touch sensors", "LIDAR", "Depth sensors", "Force sensors", "Proximity sensors"],
  },
  {
    name: "Drone Dropper",
    purpose: "Delivery",
    movement: "Flying",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Camera", "GPS", "IMU", "Ultrasonic sensors", "Barometer", "Infrared sensors"],
  },
  {
    name: "Hospital Supply Runner",
    purpose: "Delivery",
    movement: "Wheels",
    environment: "Indoors",
    control: "Mixed human and AI control",
    sensors: ["Camera", "LIDAR", "Ultrasonic sensors", "Proximity sensors", "Touch sensors"],
  },
  {
    name: "Grocery Sorting Arm",
    purpose: "Delivery",
    movement: "Stationary",
    environment: "Indoors",
    control: "Fully autonomous",
    sensors: ["Touch sensors", "Camera", "Force sensors", "Depth sensors", "Proximity sensors"],
  },
  {
    name: "Floor Sweeper Bot",
    purpose: "Cleaning",
    movement: "Wheels",
    environment: "Indoors",
    control: "Fully autonomous",
    sensors: ["Touch sensors", "Infrared sensors", "Ultrasonic sensors", "Dirt sensors", "IMU", "Cliff sensors"],
  },
  {
    name: "Window Washer Bot",
    purpose: "Cleaning",
    movement: "Tracks",
    environment: "Outdoors",
    control: "Mixed human and AI control",
    sensors: ["Camera", "Pressure sensors", "Ultrasonic sensors", "Infrared sensors", "Touch sensors", "Edge sensors"],
  },
  {
    name: "Beach Cleaner Rover",
    purpose: "Cleaning",
    movement: "Wheels",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Camera", "GPS", "Metal detector", "Ultrasonic sensors", "IMU", "Infrared sensors"],
  },
  {
    name: "Pool Scrubber Bot",
    purpose: "Cleaning",
    movement: "Tracks",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Touch sensors", "Pressure sensors", "Ultrasonic sensors", "Infrared sensors", "Water quality sensors"],
  },
  {
    name: "Home Assistant Bot",
    purpose: "Helping people",
    movement: "Wheels",
    environment: "Indoors",
    control: "Fully autonomous",
    sensors: ["Camera", "Sound sensors", "Infrared sensors", "Touch sensors", "Proximity sensors", "Ultrasonic sensors"],
  },
  {
    name: "Physical Therapy Bot",
    purpose: "Helping people",
    movement: "Legs",
    environment: "Indoors",
    control: "Human-controlled",
    sensors: ["Touch sensors", "Force sensors", "Camera", "Pressure sensors", "IMU", "Motion sensors"],
  },
  {
    name: "Guide Robot",
    purpose: "Helping people",
    movement: "Wheels",
    environment: "Indoors",
    control: "Mixed human and AI control",
    sensors: ["Camera", "LIDAR", "Sound sensors", "Ultrasonic sensors", "Proximity sensors", "Touch sensors"],
  },
  {
    name: "Pet Care Bot",
    purpose: "Helping animals",
    movement: "Wheels",
    environment: "Indoors",
    control: "Fully autonomous",
    sensors: ["Camera", "Sound sensors", "Infrared sensors", "Touch sensors", "Proximity sensors", "Motion sensors"],
  },
  {
    name: "Mars Rover Bot",
    purpose: "Exploration",
    movement: "Wheels",
    environment: "Outdoors",
    control: "Mixed human and AI control",
    sensors: ["Camera", "LIDAR", "Temperature sensor", "Radiation sensors", "Spectrometer", "IMU", "Ultrasonic sensors"],
  },
  {
    name: "Deep Sea Explorer",
    purpose: "Exploration",
    movement: "Propellers",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Camera", "Pressure sensors", "Sonar", "Temperature sensor", "Depth sensors", "Chemical sensors", "IMU"],
  },
  {
    name: "Volcano Sensor Bot",
    purpose: "Exploration",
    movement: "Legs",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Temperature sensor", "Camera", "Gas sensors", "Seismic sensors", "Infrared sensors", "IMU"],
  },
  {
    name: "Forest Mapping Drone",
    purpose: "Exploration",
    movement: "Flying",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Camera", "LIDAR", "GPS", "IMU", "Infrared sensors", "Barometer", "Humidity sensor"],
  },
  {
    name: "Dance Show Bot",
    purpose: "Entertainment",
    movement: "Legs",
    environment: "Indoors",
    control: "Human-controlled",
    sensors: ["Sound sensors", "Camera", "IMU", "Force sensors", "Proximity sensors", "Gyroscope"],
  },
  {
    name: "Theme Park Greeter Bot",
    purpose: "Entertainment",
    movement: "Wheels",
    environment: "Indoors",
    control: "Mixed human and AI control",
    sensors: ["Camera", "Sound sensors", "Touch sensors", "Proximity sensors", "Ultrasonic sensors", "Motion sensors"],
  },
  {
    name: "Robot Pet Toy",
    purpose: "Entertainment",
    movement: "Legs",
    environment: "Indoors",
    control: "Fully autonomous",
    sensors: ["Touch sensors", "Sound sensors", "Infrared sensors", "Proximity sensors", "Light sensors", "IMU"],
  },
  {
    name: "Brick Laying Bot",
    purpose: "Building",
    movement: "Tracks",
    environment: "Outdoors",
    control: "Fully autonomous",
    sensors: ["Touch sensors", "Camera", "LIDAR", "Force sensors", "GPS", "Level sensors", "Laser sensors"],
  },
  {
    name: "Road Repair Bot",
    purpose: "Fixing",
    movement: "Wheels",
    environment: "Outdoors",
    control: "Mixed human and AI control",
    sensors: ["Camera", "LIDAR", "GPS", "Temperature sensor", "Ultrasonic sensors", "Infrared sensors", "Depth sensors"],
  },
  {
    name: "Space Station Arm",
    purpose: "Building",
    movement: "Stationary",
    environment: "Outdoors",
    control: "Human-controlled",
    sensors: ["Touch sensors", "Camera", "Force sensors", "Proximity sensors", "Thermal sensors", "Strain gauges"],
  },
  {
    name: "Factory Assembly Bot",
    purpose: "Building",
    movement: "Stationary",
    environment: "Indoors",
    control: "Fully autonomous",
    sensors: ["Touch sensors", "Camera", "Force sensors", "Proximity sensors", "Laser sensors", "Depth sensors"],
  },
];

